/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommissionRouteImport } from './routes/commission'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as GalleryArtworkIdRouteImport } from './routes/gallery.$artworkId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionRoute = CommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryArtworkIdRoute = GalleryArtworkIdRouteImport.update({
  id: '/$artworkId',
  path: '/$artworkId',
  getParentRoute: () => GalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commission': typeof CommissionRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gallery/$artworkId': typeof GalleryArtworkIdRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commission': typeof CommissionRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gallery/$artworkId': typeof GalleryArtworkIdRoute
  '/gallery': typeof GalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commission': typeof CommissionRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gallery/$artworkId': typeof GalleryArtworkIdRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commission'
    | '/contact'
    | '/gallery'
    | '/sitemap.xml'
    | '/gallery/$artworkId'
    | '/gallery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commission'
    | '/contact'
    | '/sitemap.xml'
    | '/gallery/$artworkId'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commission'
    | '/contact'
    | '/gallery'
    | '/sitemap.xml'
    | '/gallery/$artworkId'
    | '/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommissionRoute: typeof CommissionRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission': {
      id: '/commission'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof CommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/$artworkId': {
      id: '/gallery/$artworkId'
      path: '/$artworkId'
      fullPath: '/gallery/$artworkId'
      preLoaderRoute: typeof GalleryArtworkIdRouteImport
      parentRoute: typeof GalleryRoute
    }
  }
}

interface GalleryRouteChildren {
  GalleryArtworkIdRoute: typeof GalleryArtworkIdRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryArtworkIdRoute: GalleryArtworkIdRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommissionRoute: CommissionRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
